// apps/react/src/components/TodayHeader.jsx
import { colorValue, formatDayMonth, formatWeekday, isDone, toKey, todayProgress } from '@beads/core';

function summary(done, total) {
  if (total === 0) return 'Пока нечего отмечать — добавьте привычку.';
  if (done === total) return `Всё на сегодня выполнено: ${done} из ${total}.`;
  return (
    <>
      Сегодня выполнено <strong>{done} из {total}</strong>.
    </>
  );
}

export default function TodayHeader({ today, habits }) {
  const { done, total } = todayProgress(habits, today);
  const key = toKey(today);

  return (
    <section className="today" aria-labelledby="today-heading">
      <h1 id="today-heading" style={{ margin: 0 }}>
        <span className="today__weekday">{formatWeekday(today)},</span>
        <span className="today__date">{formatDayMonth(today)}</span>
      </h1>
      <div className="today__progress">
        {total > 0 && (
          <div className="today-thread" aria-hidden="true">
            {habits.map((h) => (
              <span
                key={h.id}
                className={isDone(h, key) ? 'is-done' : undefined}
                style={{ '--c': colorValue(h.color) }}
              />
            ))}
          </div>
        )}
        <p className="today__summary" aria-live="polite">
          {summary(done, total)}
        </p>
      </div>
    </section>
  );
}

// apps/vue/src/components/TodayHeader.vue
<script setup>
import { computed } from 'vue';
import { colorValue, formatDayMonth, formatWeekday, isDone, toKey, todayProgress } from '@beads/core';

const props = defineProps({
  today: { type: Date, required: true },
  habits: { type: Array, required: true },
});

const progress = computed(() => todayProgress(props.habits, props.today));
const todayKey = computed(() => toKey(props.today));
</script>

<template>
  <section class="today" aria-labelledby="today-heading">
    <h1 id="today-heading" style="margin: 0">
      <span class="today__weekday">{{ formatWeekday(today) }},</span>
      <span class="today__date">{{ formatDayMonth(today) }}</span>
    </h1>
    <div class="today__progress">
      <div v-if="progress.total > 0" class="today-thread" aria-hidden="true">
        <span
          v-for="h in habits"
          :key="h.id"
          :class="{ 'is-done': isDone(h, todayKey) }"
          :style="{ '--c': colorValue(h.color) }"
        />
      </div>
      <p class="today__summary" aria-live="polite">
        <template v-if="progress.total === 0">Пока нечего отмечать — добавьте привычку.</template>
        <template v-else-if="progress.done === progress.total">
          Всё на сегодня выполнено: {{ progress.done }} из {{ progress.total }}.
        </template>
        <template v-else>
          Сегодня выполнено <strong>{{ progress.done }} из {{ progress.total }}</strong>.
        </template>
      </p>
    </div>
  </section>
</template>
